### ISSUE TITLE
[Feature Request] Support migrating to modules

### ISSUE THREAD

**Issue by piizei** [minamijoyo/tfmigrate#13]
Would be great if you could move resources to modules with tool.
Typically when reorganising the resources terraform needs to destroy and recreate them, which is not nice for databases.

Only difference in the state with resource in module or outside is field 'module' which has the name of the module the resource is in.

**Comment by piizei** [comment]
Silly me, maybe its already supported by the standard mv like _mv 'packet_device.worker' 'module.app.packet_device.worker'_?

**Comment by minamijoyo** [comment]
@piizei Yeah, moving a resource into a module has been already supported. You can use `mv old_address module.foo.new_address`

**Comment by minamijoyo** [comment]
I'll close this because it has been already supported. If you still have problems, feel free to reopen. Thanks!
