### ISSUE TITLE
OpenTofu support

### ISSUE THREAD

**Issue by chenrui333** [minamijoyo/tfmigrate#162]
Just log an issue once OpenTF stable release is available :)

(should be technically drop-in replacement of terraform)

**Comment by minamijoyo** [comment]
Hi @chenrui333,

The tfmigrate v0.3.19 now works with OpenTofu v1.6.0-alpha5 by setting the environment variable `TFMIGRATE_EXEC_PATH=tofu`.
This issue will remain open until a stable version is released.

**Comment by chenrui333** [comment]
Thanks @minamijoyo for the wonderful work, closing the issue now. 💯

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.
