### ISSUE TITLE
[Question] Don't apply state migrations to fresh workspaces in history mode

### ISSUE THREAD

**Issue by elliotpryde** [minamijoyo/tfmigrate#22]
After going through the readme, it's unclear if this tool is designed to handle newly provisioned instances of a configuration (such as a new workspace).

For the sake of simplicity, I'll just call each of these provisioned instances workspaces, although there are other ways to do this without using workspaces.

It's great that this gives us the ability to migrate the state of multiple workspaces in tandem with GitOps-friendly way with history mode, but will a newly provisioned workspace that needs no migrations have all of the historical migrations applied? To me, knowing not to apply migrations to new environments is a core requirement of a tool like this, because development teams will want to create new feature branches along with feature environments regularly.

If history mode isn't capable of handling this already, I can think of at least one way it could be done. Otherwise, if this is already possible with tfmigrate then could we document it in the readme?

**Comment by minamijoyo** [comment]
The history can be shared with all branches and your colleagues via a non-local history storage. Depends on your use-case, you can also have multiple histories with different configuration files. Separate your history and configuration file as you like. See: https://github.com/minamijoyo/tfmigrate/tree/v0.2.3#configuration-file

**Comment by minamijoyo** [comment]
I'm going to close this because no reply, but feel free reopen if you have any questions.

**Comment by joestump** [comment]
@minamijoyo this came up while reviewing this tool for our needs. We have a highly federated AWS account setup and have unique state files in each account. The same manifest is then deployed from account to account, however, like @elliotpryde's example we don't have the history in new accounts after they've been provisioned.

Is the answer to copy that history into new accounts? Cull the `tfmigrate/` after `apply`?

**Comment by minamijoyo** [comment]
Hi @joestump, Both would work, but my recommendation is the 3rd option, to use a separate migration directory and history per each account because a lifecycle of migrations belongs to resource instances to be applied, so a migration file should not be included in such a resource template module.
