### ISSUE TITLE
Bump AWS SDK version to support AWS SSO

### ISSUE THREAD

**Issue by sidewinder12s** [minamijoyo/tfmigrate#24]
SSO credential support in the go SDK landed in 1.37

https://github.com/aws/aws-sdk-go/releases/tag/v1.37.0

**Comment by minamijoyo** [comment]
@sidewinder12s Fixed in tfmigrate v0.2.4.
I've just updated the AWS SDK, but not tested it because I don't have a handy SSO setup for testing. Could you test AWS SSO?
