### ISSUE TITLE
[Feature Request] Besides Terraform, I would like to migrate state by using Terragrunt.

### ISSUE THREAD

**Issue by BeomSeo** [minamijoyo/tfmigrate#34]
sorry about bad english.

The terragrunt divides into several modules and dry the code when running plan and apply. 
But I found out that it is not compatible with tfmigrate.

When managing terraforms in multiple modules, the remote state declaration can be redundant and duplication.
Instead of declaring this setting, terragrunt helps you use it simply.
```hcl
# ./service/terragrunt.hcl
dependency "network" {
  config_path = "../network"
}
# terragrunt inserts a dependency output(from data remote state) with variable vpc_id within the terraform.
inputs = {
  vpc_id = dependency.network.output.vpc_id
}

# ./service/vars.tf
variable "vpc_id" {}
```

However, if I just try to run it on tfmigrate, the terraform plan fails because it does not have variable.

I think it's simple to run a terragrunt plan in that folder.
Will it be difficult to support this?

**Comment by minamijoyo** [comment]
@BeomSeo Thank you for your proposal.

I'm not sure how to implement it because I'm not terragrunt user.
Does the terragrunt generate backend configurations and variable files dynamically? If so, I guess it's hard to handle them by the tfmigrate. Do you know that how does the terragrunt pass them to the terraform CLI under the hood?

**Comment by BeomSeo** [comment]
yes.
Here are the links and explanations.

https://terragrunt.gruntwork.io/docs/features/inputs/

```terragrunt.hcl
inputs = {
  instance_type  = "t2.micro"
  instance_count = 10

  tags = {
    Name = "example-app"
  }
}

```

Whenever you run a Terragrunt command, Terragrunt will set any inputs you pass in as environment variables. For example, with the terragrunt.hcl file above, running terragrunt apply is roughly equivalent to:

$ terragrunt apply

### Roughly equivalent to:
```
TF_VAR_instance_type="t2.micro" \
TF_VAR_instance_count=10 \
TF_VAR_tags='{"Name":"example-app"}' \
```
terraform apply
Note that Terragrunt will respect any TF_VAR_xxx variables you’ve manually set in your environment, ensuring that anything in inputs will NOT be override anything you’ve already set in your environment.

**Comment by minamijoyo** [comment]
Thank you for the link. According the doc Terragrunt behaves as if a wrapper for Terraform CLI. I think setting an environment variable `TFMIGRATE_EXEC_PATH` to `terragrunt` may be a good start point. It allows you to customize a path to terraform CLI binary and inject a wrapper script. Have you tried it already?

**Comment by BeomSeo** [comment]
I set up TFMIGRATE_EXEC_PATH=terragrant.
Nothing is happening.
tfmigrate cli continues to track only terraform binaries.

**Comment by minamijoyo** [comment]
With `TFMIGRATE_LOG=DEBUG`, you can check to see if `TFMIGRATE_EXEC_PATH=terragrunt` was actually passed to the `MigratorOption` or not. 

```
bash-5.0# TFMIGRATE_EXEC_PATH=terragrunt TFMIGRATE_LOG=DEBUG tfmigrate plan tfmigrate_test.hcl
2021/07/29 06:45:54 [DEBUG] [main] start: tfmigrate plan tfmigrate_test.hcl
2021/07/29 06:45:54 [DEBUG] [main] tfmigrate version: 0.2.5
2021/07/29 06:45:54 [DEBUG] [command] config: &config.TfmigrateConfig{MigrationDir:".", History:(*history.Config)(nil)}
2021/07/29 06:45:54 [DEBUG] [command] option: &tfmigrate.MigratorOption{ExecPath:"terragrunt"}
2021/07/29 06:45:54 [INFO] [runner] load migration file: tfmigrate_test.hcl
2021/07/29 06:45:54 [INFO] [migrator] start state migrator plan
2021/07/29 06:45:54 [DEBUG] [executor@.]$ terragrunt version
2021/07/29 06:45:54 [DEBUG] [executor@.] failed to run command: (*exec.Error)(0xc000276560)(exec: "terragrunt": executable file not found in $PATH)
exec: "terragrunt": executable file not found in $PATH
```

**Comment by BeomSeo** [comment]
oh thank you... solve problem
I didn't know I had to set it to one command.
I thought it should work if it's in the default environment variable setting......


and the following errors may appear to users who use tgenv and terragrunt together
```
TFMIGRATE_EXEC_PATH=terragrunt TFMIGRATE_LOG=DEBUG tfmigrate plan
2021/07/29 16:55:20 [DEBUG] [main] start: tfmigrate plan
2021/07/29 16:55:20 [DEBUG] [main] tfmigrate version: 0.2.5
2021/07/29 16:55:20 [DEBUG] [command] load configuration file: .tfmigrate.hcl
2021/07/29 16:55:20 [DEBUG] [command] config: &config.TfmigrateConfig{MigrationDir:"./tfmigrate", History:(*history.Config)(0xc000276620)}
2021/07/29 16:55:20 [DEBUG] [command] option: &tfmigrate.MigratorOption{ExecPath:"terragrunt"}
2021/07/29 16:55:20 [DEBUG] [history] load migration dir: ./tfmigrate
2021/07/29 16:55:20 [DEBUG] [history] load history
2021/07/29 16:55:20 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2021/07/29 16:55:20 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/07/29 16:55:20 [DEBUG] [history] read storage &history.S3Storage{config:(*history.S3StorageConfig)(0xc0000f4200), client:(*s3.S3)(0xc000526048)}
2021/07/29 16:55:20 [INFO] [runner] unapplied migration files: [migration_1627543541.hcl]
2021/07/29 16:55:20 [INFO] [runner] load migration file: tfmigrate/migration_1627543541.hcl
2021/07/29 16:55:20 [INFO] [migrator] start state migrator plan
2021/07/29 16:55:22 [DEBUG] [executor@stage/test]$ terragrunt version
failed to parse terraform version: [INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.29.0
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.39.0

Your version of Terraform is out of date! The latest version
is 1.0.3. You can update by downloading from https://www.terraform.io/downloads.html

```

But this is not a tfmigrate or teragrunt problem.

the tgenv has a problem exporting info logs at will.

I changed it to tgswitch and set terragrunt because tgenv is not being maintained.

```
❯ TFMIGRATE_EXEC_PATH=terragrunt tfmigrate plan                    
2021/07/29 17:31:03 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2021/07/29 17:31:03 [INFO] [runner] unapplied migration files: [migration_1627543541.hcl]
2021/07/29 17:31:03 [INFO] [runner] load migration file: tfmigrate/migration_1627543541.hcl
2021/07/29 17:31:03 [INFO] [migrator] start state migrator plan
2021/07/29 17:31:05 [INFO] [migrator@stage/test] terraform version: 0.13.7
2021/07/29 17:31:05 [INFO] [migrator@stage/test] initialize work dir
2021/07/29 17:31:08 [INFO] [migrator@stage/test] get the current remote state
2021/07/29 17:31:11 [INFO] [migrator@stage/test] override backend to local
2021/07/29 17:31:11 [INFO] [executor@stage/test] create an override file
2021/07/29 17:31:11 [INFO] [executor@stage/test] switch backend to local
2021/07/29 17:31:14 [INFO] [migrator@stage/test] compute a new state
2021/07/29 17:31:17 [INFO] [migrator@stage/test] check diffs
2021/07/29 17:31:22 [INFO] [executor@stage/test] remove the override file
2021/07/29 17:31:22 [INFO] [executor@stage/test] switch back to remote
2021/07/29 17:31:26 [INFO] [migrator] state migrator plan success!
```

**Comment by amirtal-cp** [comment]
tried using same options to run migration, and got an error (logs below).
since terragrunt is expecting backend "s3".

(also tried using https://github.com/aleksanderaleksic/tgmigrate but this had other issues..)


```
❯ TFMIGRATE_EXEC_PATH=terragrunt TFMIGRATE_LOG=DEBUG tfmigrate plan

...

2021/07/30 16:09:23 [INFO] [runner] load migration file: tfmigrate/V20210713__nginx-module.hcl
2021/07/30 16:09:23 [INFO] [migrator] start state migrator plan
2021/07/30 16:09:25 [DEBUG] [executor@.]$ terragrunt version
2021/07/30 16:09:25 [INFO] [migrator@.] terraform version: 0.13.5
2021/07/30 16:09:25 [INFO] [migrator@.] initialize work dir
2021/07/30 16:09:34 [DEBUG] [executor@.]$ terragrunt init -input=false -no-color
2021/07/30 16:09:34 [INFO] [migrator@.] get the current remote state
2021/07/30 16:09:43 [DEBUG] [executor@.]$ terragrunt state pull
2021/07/30 16:09:43 [INFO] [migrator@.] override backend to local
2021/07/30 16:09:43 [INFO] [executor@.] create an override file
2021/07/30 16:09:43 [INFO] [executor@.] switch backend to local
2021/07/30 16:09:56 [DEBUG] [executor@.]$ terragrunt init -input=false -no-color -reconfigure
2021/07/30 16:09:56 [DEBUG] [executor@.] failed to run command: (*exec.ExitError)(0xc00000c1a0)(exit status 1)
failed to switch backend to local: failed to run command (exited 1): terragrunt init -input=false -no-color -reconfigure

...

[terragrunt] 2021/07/30 16:14:26 Running command: terraform init -backend-config=role_arn=arn:aws:iam::112233445566:role/builder -backend-config=bucket=terraform-state -backend-config=dynamodb_table=terraform-state-lock -backend-config=encrypt=true -backend-config=key=stg/eu-west-1/infra/eks/terraform.tfstate -backend-config=region=eu-west-1 -input=false -no-color -reconfigure

Error: Invalid backend configuration argument

The backend configuration argument "role_arn" given on the command line is not
expected for the selected backend type.


Error: Invalid backend configuration argument

The backend configuration argument "bucket" given on the command line is not
expected for the selected backend type.


Error: Invalid backend configuration argument

The backend configuration argument "dynamodb_table" given on the command line
is not expected for the selected backend type.

...
```

**Comment by amirtal-cp** [comment]
> tried using same options to run migration, and got an error (logs below). since terragrunt is expecting backend "s3".
> 
> (also tried using https://github.com/aleksanderaleksic/tgmigrate but this had other issues..)
> 
> ```
> ❯ TFMIGRATE_EXEC_PATH=terragrunt TFMIGRATE_LOG=DEBUG tfmigrate plan
> 
> ...
> 
> 2021/07/30 16:09:23 [INFO] [runner] load migration file: tfmigrate/V20210713__nginx-module.hcl
> 2021/07/30 16:09:23 [INFO] [migrator] start state migrator plan
> 2021/07/30 16:09:25 [DEBUG] [executor@.]$ terragrunt version
> 2021/07/30 16:09:25 [INFO] [migrator@.] terraform version: 0.13.5
> 2021/07/30 16:09:25 [INFO] [migrator@.] initialize work dir
> 2021/07/30 16:09:34 [DEBUG] [executor@.]$ terragrunt init -input=false -no-color
> 2021/07/30 16:09:34 [INFO] [migrator@.] get the current remote state
> 2021/07/30 16:09:43 [DEBUG] [executor@.]$ terragrunt state pull
> 2021/07/30 16:09:43 [INFO] [migrator@.] override backend to local
> 2021/07/30 16:09:43 [INFO] [executor@.] create an override file
> 2021/07/30 16:09:43 [INFO] [executor@.] switch backend to local
> 2021/07/30 16:09:56 [DEBUG] [executor@.]$ terragrunt init -input=false -no-color -reconfigure
> 2021/07/30 16:09:56 [DEBUG] [executor@.] failed to run command: (*exec.ExitError)(0xc00000c1a0)(exit status 1)
> failed to switch backend to local: failed to run command (exited 1): terragrunt init -input=false -no-color -reconfigure
> 
> ...
> 
> [terragrunt] 2021/07/30 16:14:26 Running command: terraform init -backend-config=role_arn=arn:aws:iam::112233445566:role/builder -backend-config=bucket=terraform-state -backend-config=dynamodb_table=terraform-state-lock -backend-config=encrypt=true -backend-config=key=stg/eu-west-1/infra/eks/terraform.tfstate -backend-config=region=eu-west-1 -input=false -no-color -reconfigure
> 
> Error: Invalid backend configuration argument
> 
> The backend configuration argument "role_arn" given on the command line is not
> expected for the selected backend type.
> 
> 
> Error: Invalid backend configuration argument
> 
> The backend configuration argument "bucket" given on the command line is not
> expected for the selected backend type.
> 
> 
> Error: Invalid backend configuration argument
> 
> The backend configuration argument "dynamodb_table" given on the command line
> is not expected for the selected backend type.
> 
> ...
> ```

(for reference)

this was resolved by removing terragrunt backend generation block. i.e.
```
generate "backend" {
  path      = "backend.tf"
  if_exists = "skip"
  contents  = <<EOF
terraform {
  backend "s3" {}
}
EOF
}
```

replacing generation with the following addition to `remote_state` block. i.e.
```
remote_state {
  backend = "s3"
  config = {
    bucket         = bucket_name
... additional config ...
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

**Comment by caseycs** [comment]
I'l like to share my experience of combining the tool with terragrunt.

Solution with `TFMIGRATE_EXEC_PATH` works like a charm, but additional wrapper makes migrations incredibly slow, especially when you have 30+ resources. The workaround I found is to use generated pure terraform work directory. To find exact path this command can be used:

```bash
terragrunt plan -lock=false --terragrunt-debug  | head -n1
```

Next step is to copy/rename tfvars file generated by terragrunt towards one of the [automatically processed patters](https://developer.hashicorp.com/terraform/language/values/variables).

```bash
cp terragrunt-debug.tfvars.json terragrunt-debug.auto.tfvars.json
```

And from there execute `tfmigrate`
