### ISSUE TITLE
Error when migration script contains state manipulations for list items

### ISSUE THREAD

**Issue by aivong2** [minamijoyo/tfmigrate#38]
Hi,

For a state manipulation containing brackets (i.e. when moving list items), I saw the following error:
`Index brackets must contain either a literal number or a literal string`

Example migration script:
```terraform
migration "state" "test" {
  actions = [
    "mv module.peering.aws_route.routes[0] module.peering.aws_route.routes['rtb-1234567']"
  ]
}
```

I was upgrading terraform versions and one of my changes was updating a block using count to use for_each. I think a list had become a set. I noticed the underlying command tfmigrate was running on my behalf was missing quotes around the resources with brackets as well as quotes within the brackets:
`terraform state mv -state=/var/folders/9l/9n0dly0d7yz_qg1jzbfjl9wh0000gn/T/tmp803107815 -backup=/dev/null module.peering.aws_route.routes[0] module.peering.aws_route.routes-common[rtb-1234567]`

**Comment by minamijoyo** [comment]
Have you tried `\'` or `\"` ?

**Comment by aivong2** [comment]
Hi,

Yes I had tried escaping with single and doublequotes but the result was the same error.

**Comment by minamijoyo** [comment]
@aivong2  Ahh, I remembered #5. Using `for_each` was a bit tricky. Have it a try:

```hcl
migration "state" "test" {
  actions = [
    "mv module.peering.aws_route.routes[0] 'module.peering.aws_route.routes[\"rtb-1234567\"]'"
  ]
}
```

**Comment by aivong2** [comment]
@minamijoyo thanks for following up! I have tried that combination as well :( I think one of the issues was the brackets requiring double quotes for the integer index but 'module.peering.aws_route.routes[\"0\"]' also did not work for me. The escaped quotes were trimmed off from my testing. I got around my issue by actually simulating on a basic level what I thought the tfmigrate tool would do. I made a local copy of the remote state and executed state changes against that to generate a plan. Unfortunately it means now I am not able to reproduce this issue anymore. We can close and reopen this later if needed

**Comment by minamijoyo** [comment]
I tested the minimum reproduction case with the current latest tfmigrarte v0.2.7 + terraform v1.0.5 and confirmed that it worked.

before

```main.tf
resource "null_resource" "foo" {
  count = 1
}
```

after

```main.tf
resource "null_resource" "foo" {
  for_each = toset(["bar"])
}
```

migration

```hcl
migration "state" "test" {
  actions = [
    "mv null_resource.foo[0] 'null_resource.foo[\"bar\"]'",
  ]
}
```

```
bash-5.0# tfmigrate plan tfmigrate_test.hcl
2021/08/25 02:38:16 [INFO] [runner] load migration file: tfmigrate_test.hcl
2021/08/25 02:38:16 [INFO] [migrator] start state migrator plan
2021/08/25 02:38:17 [INFO] [migrator@.] terraform version: 1.0.5
2021/08/25 02:38:17 [INFO] [migrator@.] initialize work dir
2021/08/25 02:38:19 [INFO] [migrator@.] switch to remote workspace default
2021/08/25 02:38:19 [INFO] [migrator@.] get the current remote state
2021/08/25 02:38:20 [INFO] [migrator@.] override backend to local
2021/08/25 02:38:20 [INFO] [executor@.] create an override file
2021/08/25 02:38:20 [INFO] [migrator@.] creating local workspace folder in: terraform.tfstate.d/default
2021/08/25 02:38:20 [INFO] [executor@.] switch backend to local
2021/08/25 02:38:23 [INFO] [migrator@.] compute a new state
2021/08/25 02:38:23 [INFO] [migrator@.] check diffs
2021/08/25 02:38:25 [INFO] [executor@.] remove the override file
2021/08/25 02:38:25 [INFO] [executor@.] remove the workspace state folder
2021/08/25 02:38:25 [INFO] [executor@.] switch back to remote
2021/08/25 02:38:28 [INFO] [migrator] state migrator plan success!
```

**Comment by minamijoyo** [comment]
@aivong2 I'm going to close this, but feel free to reopen if you can reproduce the error.
