### ISSUE TITLE
Allow passing in a url to a tfmigrate file

### ISSUE THREAD

**Issue by nitrocode** [minamijoyo/tfmigrate#92]
```
tfmigrate plan https://raw.githubusercontent.com/minamijoyo/tfmigrate/master/test-fixtures/storage_s3/.tfmigrate.hcl
tfmigrate apply https://raw.githubusercontent.com/minamijoyo/tfmigrate/master/test-fixtures/storage_s3/.tfmigrate.hcl
```

**Comment by minamijoyo** [comment]
I remember having a conversation with you about this on the hangops slack a long time ago, but the migration file is tied to the root module and cannot be used as a generic module upgrade template. That is, I don' think that it makes sense to load a remote URL. If you still need it, please describe your use case and reopen it.
